version: '3.8'

services:
  glpi-reports:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glpi-reports-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}     
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
    networks:
      - default
      - glpi-target-network

networks:
  default:
  glpi-target-network:
    name: glpi-dev-network # 👈 พิมพ์ชื่อจริงลงไปตรง ๆ เลย ไม่ต้องใช้ตัวแปร ${NETWORK_NAME}
    external: true     
